### ISSUE TITLE
reporting "UMI missing" with '-U' has already been set

### ISSUE THREAD

**Issue by QidiFeng** [velocyto-team/velocyto.py#101]
Sorry that I reopen the issue again, since my problem still has not been solved with version 0.17.11. My data is from Fluidigm C1 alignment bam file, and the command is 'velocyto run -U -o test SRR1275387.transcript.bam Homo_sapiens.GRCh38.83.gtf'. However, it is reporting error:
"OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag."

Here are the heads of my bam file:
SRR1275387.3 3 length=99	77	*	0	0	*	*	0	0	TTGTAGCCCAGGATGAGTCCCTCAGCGTGACGCAGTAGACTAGTAGCATCCCGATCTTTTCCCTATCTAATTCACCTCCTATTAGGAGCCGATCGTGCT	AAAAA3FFFAA1FGCGGGG1FGHF1FEEE0CAE?0AF1BFEB1D22D2FGGGG/AEGHFHHHHHGHHGD1DGHHFFHFHHFFD2DB10B?//>E@ECFF	XM:i:0
SRR1275387.3 3 length=99	141	*	0	0	*	*	0	0	AGCACGATCGGCTCCTAATAGGAGGTGAATTAGATAGGGAAAAGATCGGGATGCTACTAGTTTACTGCGTCACGCTGAGGGACTCATCCTGGGCTACAA	1AAAA1AAA@ADCEFG1BGGFGHGGGEHHFFFC1GHFHHHCFHHEHHH?A/ECGHHFH112BFHHFGHGGGGGCGFCEGEEGGGHHFHHHFHEFHAGH1	XM:i:0

Could you please help me to figure out what is going on? Thank you very much!

**Comment by gioelelm** [comment]
Ok I see the problem... If the bam file is the one of a single cell, you
should use the -c flag, you can even specify multiple files using a
wildcard completion as soon as -c is there.

Otherwise if the file contains many cells (e. g. a full Fluidigm chip) you
are ignoring the requirement to have a flag with a cell barcode for each
read entry, as specified here :
http://velocyto.org/velocyto.py/tutorial/cli.html#requirements-on-the-input-files

The way to add the tag depends on your preference, I reccomend a simple
loop in python and pysam.

**Comment by gioelelm** [comment]
Furthermore I am a bit confused, is the extract of the file really a mapped
bam file. It does not look like...

**Comment by QidiFeng** [comment]
Oh, right. Adding "-c" did solve the problem and I need to re-check the format of my bam file. Thank you very much!
