### ISSUE TITLE
Quantify the velocyties

### ISSUE THREAD

**Issue by manarai** [velocyto-team/velocyto.py#157]
Hi,

I run velocito on inflammed inmmune cells between different aged mice and I see a trend, the velocities ( arrows on my umap) going from normal to inflammed cells become smaller with age correlating with reduced immune function in this particular assay. Does it make sense to use the average vector length for every embedded velocities and compare between different age sample? I would like to show and say in a more quantitative way that the propensity of these immune cells to become activated, based on the average velocities, decreases with age.

**Comment by gioelelm** [comment]
I would be very careful in using velocity for predictions beyond few hours.
This being said, what you want to do in your case is to take several marker genes and show the phase portrait colored by time point. The position of the different cells in the phase portait should be distinguishable, and provide a qualitative evidence. To be more quantitative you can bootstrap and prove what you are observing is indeed significant.

Very important: I your case and, more in general, in any case where if you are using velocyto accross several indipendent biological samples that then you want to make conlcusions about I reccomand to use **group_constraint** in the **knn_imputation** function to avoid the data from different sample gets smoothed with the others.

Also, please if a question is not about a velocyto bug but rather about a request of advice on its usage I would prefer to take the questions by email. Otherwise, we tend to overcrowd this platform, and people who look for bug solutios will have an harder time. Thanks

**Comment by mschilli87** [comment]
@gioelelm:
> Also, please if a question is not about a velocyto bug but rather about a request of advice on its usage I would prefer to take the questions by email. Otherwise, we tend to overcrowd this platform, and people who look for bug solutios will have an harder time. Thanks

I'd recommend an [issue template](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) to communicate this.
