### ISSUE TITLE
Execution time for 10X samples

### ISSUE THREAD

**Issue by idalarsson** [velocyto-team/velocyto.py#159]
Hello,

First of all, thank you for a very exciting tool!

I am currently running velocyto on a 10X sample and was wondering about the execution time. The ~3h note in the tutorial, what CPU power and seq depth is that counted on approximately?

My analysis has been running for 3.5 hours and is still on the message "Marking up chromosome 1" so I'm beginning to wonder if there is something wrong with my setup, but I don't want to abort the run if it's just that my computer is a bit weak.

//Ida

**Comment by gioelelm** [comment]
What machine are you using? It sounds like it might be a memory problem.

**Comment by idalarsson** [comment]
Right now I'm running it on a laptop, 16G 64 bit, since I couldn't get it to work on my windows PC (stationary).

**Comment by gioelelm** [comment]
Ok then the problem is that your memory gets filled up. This is a step that should be done on a server not on a laptop really where maybe only 8-9 of that Gb of memory are actually available at any given point.
If you really want to run it on a laptop you can make sure you are specifying the valid barcode list. This should reduce the memory usage, avoiding that low counts droplets (empty/background) are allocated a column of the data matrix… however from the info you provide your problem seem to arise even before the point where not specifying a barcode list would cause trouble.

/Gioele

**Comment by idalarsson** [comment]
Ok thank you, then I will try it on the server instead :) Thanks for your help!

**Comment by denvercal1234GitHub** [comment]
@gioelelm - When you get a chance, would you mind helping me know how to obtain the valid barcode list? I ran the 10x cellranger count for my samples (I have 2 donors and each donor has 2 cell populations that were sequenced, so total I have 4 bam samples).

When I ran run10x I encountered the problem described in #320 . Maybe providing the barcode list will help? 

I will also try to sort the bams by cell barcode then by position by samtools.

Thank you so much.

**Comment by denvercal1234GitHub** [comment]
Solved for my case. It was indeed memory issue. But instead of asking for more memory, I did samtools sort the bam first. But the issue is that after I samtools sort the possorted bam file, run10x ran and still gave me a loom file yet in the error log it says it did not find the index file for my cellsorted_possorted bame (see #321). Any thoughts?
