### ISSUE TITLE
velocyto .normalize - divide by zero encountered in true_divide

### ISSUE THREAD

**Issue by joshua-gould** [velocyto-team/velocyto.py#21]
import velocyto as vcy
vlm = vcy.VelocytoLoom("myloomfile.loom")
vlm.normalize("S", size=True, log=True)

>>>vlm.default_filter_and_norm()
/miniconda/lib/python3.6/site-packages/velocyto/analysis.py:670: RuntimeWarning: divide by zero encountered in true_divide
  adj_factor = predicted / y
/miniconda/lib/python3.6/site-packages/velocyto/analysis.py:707: RuntimeWarning: divide by zero encountered in true_divide
  self.U_sz[:, ~self.small_U_pop] = self.U_sz[:, ~self.small_U_pop] * (np.median(self.U_sz[:, ~self.small_U_pop].sum(0)) / self.U_sz[:, ~self.small_U_pop].sum(0))
/miniconda/lib/python3.6/site-packages/velocyto/analysis.py:707: RuntimeWarning: invalid value encountered in multiply
  self.U_sz[:, ~self.small_U_pop] = self.U_sz[:, ~self.small_U_pop] * (np.median(self.U_sz[:, ~self.small_U_pop].sum(0)) / self.U_sz[:, ~self.small_U_pop].sum(0))

**Comment by gioelelm** [comment]
Not super clear from how you formatted the text of the issue, but I guess it  is vlm.default_filter_and_norm() that is throwing the error not vlm.normalize("S", size=True, log=True).

If that is the case keep in mind that methods in velocyto are supposed to be called in a specific order for everything to work correctly. Are you following the order shown I  the notebooks or the tutorial? Also the methods starting with "defaults"  are kind of macroa. They logically pack a set of methods calls using some heuristic as arguments and are more intended as a reference then a facility. The idea is that users can look at the source code and try to adapt the steps to their pipeline. I should be more clear about it in the tutorial. 

In the particular case there seems to be some NaN generation due to a division by zero. Of course this should not happen. Probably the heuristic for the feature selection is too permissive for your dataset.
