### ISSUE TITLE
Installation on Mac OS

### ISSUE THREAD

**Issue by SamAllon** [velocyto-team/velocyto.py#25]
Has team velocyto tested the installation on the Mac operating system? Myself and colleagues have have run into roadblocks with the clang compiler. gcc-4.8 appeared to solve the issue for one of us, allowing her to successfully install velocyto, but that compiler is not compatible with the latest Mac OS 10.13.

Do you have general advice for installing velocyto on a Mac? Would really appreciate it!

**Comment by gioelelm** [comment]
Unfortunately updating to the latest version of OS 10 always brings a lot of problems with it if you use your Mac for software development / programming. Personally, I don't update earlier than 6months-1year from the initial release, and never encountered problems that way.

I also usually rely on the compilers provided by conda. Right now I am using this on my OS 10.12:

```
gcc 4.8.5 8
-----------
file name   : gcc-4.8.5-8.tar.bz2
name        : gcc
version     : 4.8.5
build string: 8
build number: 8
channel     : defaults
size        : 55.1 MB
arch        : x86_64
date        : 2016-10-28
license     : GPL3
license_family: GPL3
md5         : fd6c71a8b900684cbb2c2edba58ff9c1
noarch      : None
platform    : darwin
url         : https://repo.continuum.io/pkgs/free/osx-64/gcc-4.8.5-8.tar.bz2
dependencies:
    cloog 0.18.0
    gmp >=4.3.2
    isl >=0.10,<=0.14
    mpc >=0.8.1
    mpfr >=2.4.2
```

Furthermore velocyto is not thought to work on laptops, because of the intrinsic memory usage requirements for some functions makes it unpractical to run them with just 16GB of RAM. So we don't plan to add extensive support for OS for this right now. 

However, if you still want to be able to install on Mac despite this there might be a solution.
Notice that in the github repository we distribute a precompiled `.so` extension for Mac/Darwin architecture ``speedboosted.cpython-36m-darwin.so``. So, in principle, this can be installed from source skipping the compilation step, doing the following:

Clone the repo
`git clone https://github.com/velocyto-team/velocyto.py.git`

modify the file `velocyto.py/setup.py` in the following way:

```
C_COMPILE = False
USE_CYTHON = False
```

install from source:
 - Make sure you unsinstalled previous versions `pip uninstall velocyto`
 - Move in the folder`cd velocyto.py`
 - install by `pip install .` (notice the trailing dot)

**Comment by SamAllon** [comment]
Thanks for the quick reply, Gioele! I'll see whether I can get the package installed on a cluster instead.

**Comment by ektapathak08** [comment]
hi,
I tried to install the velocyto package using the above method but it gives the following error 


import velocyto as vcy



ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import velocyto as vcy

File ~/miniconda3/lib/python3.9/site-packages/velocyto/__init__.py:13, in <module>
     11 from .metadata import MetadataCollection, Metadata
     12 from .neighbors import BalancedKNN, convolve_by_sparse_weights
---> 13 from .estimation import fit_slope, _fit1_slope, clusters_stats
     14 from .serialization import dump_hdf5, load_hdf5
     15 from .analysis import VelocytoLoom, scatter_viz, ixs_thatsort_a2b, load_velocyto_hdf5

File ~/miniconda3/lib/python3.9/site-packages/velocyto/estimation.py:7, in <module>
      5 from typing import *
      6 from sklearn.neighbors import NearestNeighbors
----> 7 from .speedboosted import _colDeltaCor, _colDeltaCorLog10, _colDeltaCorSqrt
      8 from .speedboosted import _colDeltaCorpartial, _colDeltaCorLog10partial, _colDeltaCorSqrtpartial
     11 def colDeltaCor(emat: np.ndarray, dmat: np.ndarray, threads: int=None) -> np.ndarray:

ModuleNotFoundError: No module named 'velocyto.speedboosted'

I am using MacBook Pro with  chip :Apple M1 Max

any suggestion?

Best,
Ekta

**Comment by anshu957** [comment]
I'm on M1 mac as well and I was able to successfully installed `velocyto` using following :

1. Check if you have a gcc compiler in your homebrew directory. The gcc is located at `/opt/homebrew/Cellar/gcc/`
2. Once you have that, depending on the gcc version, you can run `CC=/opt/homebrew/Cellar/gcc/XXXX/bin/gcc-XX pip install velocyto`, where `XXXX` is the subfolder (for me it was 11.3.0_2) and `XX` is the gcc version (for me it was 11).

Hope that helps.
