### ISSUE TITLE
How to fix MemoryError (f" bam file #{k} could not be sorted by cells. \n\ in run10x and run?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [velocyto-team/velocyto.py#320]
Hi there, 

I encountered issue with "Out of memory" when I run10x in velocyto. Looking at the .err file returned from the server cluster, i had issues shown below. 

MemoryError (f" bam file #{k} could not be sorted by cells. \n\ in run10x

It further says the error is probably related to an old version of samtools, please install samtools >= 1.6 but I checked and samtools  version 1.10 was used. 

It says to set the --samtools_memory option to a value compatible with my system. Otherwise sort mannually by samtools 

```
sort -l [compression] -m [mb_to_use]M -t [tagname] -O BAM -@ [threads_to_use] -o cellsorted_[bamfile] [bamfile]
```

Anyone has any suggestion how to fix this error? 

Thank you so much!

<img width="1189" alt="Screen Shot 2021-11-15 at 5 32 59 PM" src="https://user-images.githubusercontent.com/62179082/141827654-bc1d2993-f4f2-4a93-8424-63b7e36cde89.png">

**Commands I had in my sh script to run on our server cluster:**

<img width="865" alt="Screen Shot 2021-11-15 at 7 13 46 PM" src="https://user-images.githubusercontent.com/62179082/141840391-feafc338-ca1d-4ae6-a3ff-eae1bce7312f.png">

**Comment by denvercal1234GitHub** [comment]
After some discussions with @cdi in #76, I tried the code below, but I still got error from the cluster "Run time 00:32:27, OUT_OF_MEMORY."

This time, I made sure that the packages were installed within my conda environment. 
I included the cell barcodes file 
I checked the bam file 
I used the right gtf 

Anyone has any other suggestions?

Thank you so much!

<img width="731" alt="Screen Shot 2021-11-17 at 1 45 40 AM" src="https://user-images.githubusercontent.com/62179082/142094032-d71ff7c5-9605-4f98-a60f-8866216d1f6b.png">

**Comment by denvercal1234GitHub** [comment]
Now, I will try to sort the bam file first as below and see if that helps. Fingers-crossed

<img width="729" alt="Screen Shot 2021-11-17 at 2 39 04 AM" src="https://user-images.githubusercontent.com/62179082/142111474-ae1f4614-6f1b-4111-a298-361cf9e2c013.png">

**Comment by AAA-3** [comment]
Hi @denvercal1234GitHub 

Saw your comment in my issue's thread - not sure how I can help here. 

To answer your questions:
I ended up running velocyto with the` run10X command` and gave up trying to use `run`. 
I uninstalled and reinstalled samtools, making sure it as the most updated version.
I made sure the  environment had no clashes (`conda update --all` seems to do the trick) but made sure that my samtools was not downgraded. 

If the correct version of samtools and all other packages are up to date, Velocyto will run samtools to sort out your BAM files automatically and have it run in the background while it continues with its own computation.

**Comment by AAA-3** [comment]
From what I have read on these forums, the memory is only an issue if your Samtools is not up to date (I just checked and the latest version is 1.14)

**Comment by denvercal1234GitHub** [comment]
@AAA-3 -- In our cluster, we have the samtools/1.10 which should work fine I think? 🥵

**Comment by AAA-3** [comment]
I can't remember what the minimum version of samtools was needed but I think that 1.10 should be fine. 

I used the possorted_...BAM file given by cell ranger - I did not change my BAM file name as is suggested in some other forums because Samtools (when evoked by Velocyto) will create a sorted one for you (it will sort it by cell ID, cellranger only sorts by position)

CODE:
`velocyto run10x -m mm10_repeat_msk.gtf .../outs .../genes.gtf`

where -m is followed by the address of my mask file; then I have my cellranger "outs" folder directory address; then finally the address of my reference GTF file.

Also, just make sure that you have also pysam installed - in one of the forums here someone missed out on that package which gave them troubles as well.

**Comment by denvercal1234GitHub** [comment]
@AAA-3 -- Now, when I rerun the run10x, another error appeared "IndexError - list index out of range as reported in #183 

@RBBurl1227 any suggestions?

**Comment by denvercal1234GitHub** [comment]
Trying to delete the "exon_number" field in my genes.gtf file according to the suggestions from #117 after seeing my genes.gtf file also contain the exon_number field. Will update how it goes. 

<img width="1285" alt="Screen Shot 2021-11-17 at 7 45 24 PM" src="https://user-images.githubusercontent.com/62179082/142271590-6b0e2c3f-3c34-4e9b-875b-1917dfef6289.png">

**Comment by denvercal1234GitHub** [comment]
This is how my genes.gtf looked before deletion of exon_number field: 
<img width="1287" alt="Screen Shot 2021-11-17 at 7 43 40 PM" src="https://user-images.githubusercontent.com/62179082/142271365-4397887b-bb54-498e-8596-8ba2323a036e.png">

I deleted the "; exon_number X" with X being a number field from my gtf and reran run10x, but the error of "IndexError: list index out of range" still there:

<img width="900" alt="Screen Shot 2021-11-17 at 11 14 24 PM" src="https://user-images.githubusercontent.com/62179082/142297513-ebea1019-7252-4bd0-bb64-9c3a5da031e8.png">

This is how my genes.gtf looked after deletion:

<img width="1034" alt="Screen Shot 2021-11-17 at 11 17 43 PM" src="https://user-images.githubusercontent.com/62179082/142297820-6daac04f-f1a3-4f8f-8b84-085e10be487a.png">

**Comment by AAA-3** [comment]
I can't help with the GTF file - I don'T even know how you managed to edit it :O

**Comment by cdiaz45** [comment]
@denvercal1234GitHub I would make sure that not only the tools are installed but also the versions mentioned. Also if you can, just take a portion of your bam say chr1 and run it. If it doesn't then you know it is not memory related. If they provide test data, I would also run that. In addition, you can validate your gtf with gtf validator I think it is called or something along those lines. It will tell you if something is weird going on and where.

**Comment by denvercal1234GitHub** [comment]
Thank you all. 

I finally got it to generate loom file. I think there were two main issues with the run10x:

+ For my cluster which might be different for your cluster, do not create virtual environment. Just use the packages installed by the server administrators
+ Ensure you have the directory of the count output as directiory that contains the outs folder.
+ Ensure you have barcodes file as zip version and not unzipped!
+ Ensure you have the right gtf (it should be one located in /genes/genes.gtf) and masked files downloaded correctly (do md5 checksum if needed). 
+ Ensure you do the manual sorting first of your bam file and that the cellsorted_possorted bam and the original bam.bai files are in the same directory 

I wish everyone the best of luck! I managed to get it to generate a loom file, but when I examined the error log, it said "Could not retrieve index file for the cellsorted_possorted_genome_bam.bam." -- Will make another issue!

<img width="883" alt="Screen Shot 2021-11-20 at 1 19 24 PM" src="https://user-images.githubusercontent.com/62179082/142727861-0271511f-c12c-43b9-98d6-f23443d97f83.png">

**Comment by wbvguo** [comment]
## issue
I faced the same error with `run10x` when submitting job arrays on a computing cluster (samtools' version is compatible). Initially, I thought the error was due to insufficient memory allocation for each job. Thus, I ran a small test and increased the job's memory limit from 32 GB,  64 GB, and 96 GB to 192 GB, but the error still appeared.

## debug
Then, I began to think this was not a memory issue; the error indicated the job was terminated when sorting the bam file. The bam file chunks in the working folder indicated sorting was interrupted. Thus, I began to speculate I could be facing a storage issue, which prevents the sorted data (in memory) from writing to disk.

The storage issue did not enter my mind at first sight, as I had enough space to host the processed data (although I was not far from the quota limit). However, the final step of sorting involves merging the intermediate chunked BAM files into a single integrated BAM file, which increases the overall storage requirement beyond that of the final processed data. Running all jobs concurrently further amplified this storage demand.

## Solution
The issue disappears when I reduce the number of concurrent jobs (the extreme solution is to run jobs sequentially).

This issue might only appear in my case, but I still posted it here in case anyone has the same scenario and needs some hints.
