### ISSUE TITLE
setup.py error - package_data: dict = {}

### ISSUE THREAD

**Issue by jonathangriffiths** [velocyto-team/velocyto.py#36]
Hello,

I'm trying to install velocyto into an ubuntu-based singularity image. However, I am failing at the install with the error in the title:
```
+ pip install velocyto
Collecting velocyto
  Downloading velocyto-0.12.1.tar.gz (180kB)
    100% |################################| 184kB 2.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rCTsse/velocyto/setup.py", line 14
        package_data: dict = {}
                    ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rCTsse/velocyto/
ABORT: Aborting with RETVAL=255

```

I can see this line in the setup.py file, but I'm not familiar enough with python to understand what this line is trying to do.

Concerning the compute environment, the recipe includes these steps with regard to python:

```
apt-get -y install python python3 python-pip python3-pip git
pip install --upgrade pip
pip3 install --upgrade pip

pip install numpy scipy cython numba matplotlib scikit-learn h5py click pysam
pip install velocyto
```

Do you have any ideas what is causing this?

Thanks!

**Comment by gioelelm** [comment]
I am almost sure that the problem is that the pip you are using belongs to a python 2.7 installation.
The error is basically complaining of a new syntax that is not python2.7 compatible.

You probably have python 3.x installed but your installation is defaulting to use the python 2.7 ``pip`` command. Maybe try to use ``pip3 install``?
 
We recommend to use anaconda/miniconda environment for easy installation, so if you can, move to that way of installing.... Even if you solve this with pip3 there might be other problems popping up (compiler related for example)

**Comment by jonathangriffiths** [comment]
You were right - conda solved the problem.

pip3 did not, though. I had tried this before too, and ought to have mentioned it. Thanks for the help!
