### ISSUE TITLE
velocyto suck on writing loom file

### ISSUE THREAD

**Issue by tmfs10** [velocyto-team/velocyto.py#39]
Hi,

velocyto seems stuck on the writing of the loom file -- currently it's been stuck on the line below for 3 hours.

ds = loompy.create(filename=outfile, matrix=spliced, row_attrs=ra, col_attrs=ca, dtype="float32")

**Comment by slinnarsson** [comment]
That’s not right. Should take a minute at most. How big is the dataset? If it is close to your RAM maybe the computer is [thrashing](https://en.m.wikipedia.org/wiki/Thrashing_(computer_science))?

**Comment by tmfs10** [comment]
The bam file is ~40 GB. While I think I'm operating close to the RAM limit, at the point that line is run, all the matrices have already been created and allocated I think so RAM shouldn't be an issue, right?

**Comment by gioelelm** [comment]
Could you please report the command that you are running?
I suspect that you are running without specifying a valid barcode list. In that case you will be generating a loom file that has as many columns as there are unique barcodes (including sequencing errors), that is of course at least one order of magnitude more than expected.

**Comment by gioelelm** [comment]
also.... even if matrixes were preallocated, memory could still be an issue if there is a casting from float64 to float32.

**Comment by tmfs10** [comment]
The command I'm running is

velocyto run -b bam_neuron/raw_gene_bc_matrices/mm10/barcodes.tsv -m mm10_rmsk.gtf -o temp possorted_genome_bam.bam genes.gtf

**Comment by tmfs10** [comment]
Is there any documentation on what's expected in the loom file? I was thinking of writing my own script to preprocess and feed that into velocyto if I can't get the preprocessing to work.

**Comment by gioelelm** [comment]
ok you are using the wrong barcode set, you should be using "filtered_gene_bc_matrices"

**Comment by tmfs10** [comment]
> But the "preprocessing" is not so trivial as you think... I guess... Or maybe you have already a working pipeline to do that.

I think the latest cellranger software annotates reads with whether they map to introns or not? So that should be able to distinguish between spliced and unspliced reads right?

**Comment by gioelelm** [comment]
I might be wrong but as far as I know there is no a standard intron annotation, .gtf files contain exons annotations and cellranger (at least the version that I have been using) does not report mappings to introns in that sense. 

Furthermore is not only a matter of reads, it is a matter of molecules! You might have two reads with the same molecular barcode that map to different position of the gene (because of how the library prep is performed).  Also you can have mappings that might be interpreted as introns or exons depending which transcript model you are considering. 
This is only some of the complications we deal with in velocyto.py there are some extra corner cases to deal with.

**Comment by gioelelm** [comment]
I guess the problem is to be considered solved. Feel free to reopen if this is not the case,

**Comment by felixhorns** [comment]
Hello,

I seem to also be having an issue where velocyto is stuck writing the loom file.

Standard out reads:
2018-03-19 19:03:09,404 - DEBUG - Counting done!
2018-03-19 19:03:09,416 - DEBUG - Generating output file /path/to/sample/velocyto/sample.loom
2018-03-19 19:03:09,417 - DEBUG - Collecting row attributes
2018-03-19 19:03:09,592 - DEBUG - Generating data table
2018-03-19 19:03:15,065 - DEBUG - Writing loom file

The loom file was touched, but is empty:
-rw-r--r-- 1 user group 0 Mar 19 19:03 /path/to/sample/velocyto/sample.loom

The velocyto process is still running:
user   8484 13.8 22.0 6615696 5449500 pts/9 D    Mar19 133:00 /path/to/anaconda2/envs/py36/bin/python /path/to/anaconda2/envs/py36/bin/velocyto run10x --samtools-threads 12 /path/to/sample /path/to/reference/genes.gtf

In a previous instance, the velocyto process was still running ~5 days later and the loom file was still empty.

I encountered this problem with loompy-2.0.7. I downgraded to loompy-1.1.0 and still had the same problem.

Any suggestions?

Thanks.

**Comment by gioelelm** [comment]
The problem is related to the fact that you are probably not filtering the barcodes using valid barcode list, this is really a recommended option step, therefore the matrix generated will be huge (one row for each barcode even the ones supported by one UMI) and then your computer encounters memory problems such as  thrashing.

Furthermore I do not recommend in any way downgrading. Instead you can upgrade to the current development version installing from source.

Usually if velocyto takes more than 5h to finish something was wrong in the files or input you passed.

**Comment by GuidoBarzaghi** [comment]
Hi Gioele! I am facing the exact same problem: velocyto run10x gets stuck when it's time to write the loom file. I have been looking into passing the correct barcode list and I saw that the run10x wrapper is supposed to grab it automatically (I checked that the path matches the one in the source code). Regardless of this, I also tried passing it explicitly but I got the same result. Do you have any suggestion on how to proceed?

Here is the command line I used to generate several loom files:

/path/to/velocyto run10x -m path/to/hg19_rmsk.gtf path/to/SAMPLEFOLDER path/to/Homo_sapiens.GRCh37.82.gtf

and when the above failed I tried:

/path/to/velocyto run --bcfile path/to/SAMPLEFOLDER/outs/filtered_gene_bc_matrices/hg19/barcodes.tsv --outputfolder path/to/SAMPLEFOLDER/velocyto --sampleid SAMPLEID -m path/to/hg19_rmsk.gtf path/to/SAMPLEFOLDER/outs/possorted_genome_bam.bam path/to/Homo_sapiens.GRCh37.82.gtf
