### ISSUE TITLE
error occurred at running vlm.default_filter_and_norm()

### ISSUE THREAD

**Issue by goldfish500** [velocyto-team/velocyto.py#45]
I was using the default filtering and normalization but got this error. Is there way to get around this? Thanks!

>>> vlm.default_filter_and_norm()
/usr/home/anaconda3/lib/python3.6/site-packages/velocyto/analysis.py:695: RuntimeWarning: divide by zero encountered in true_divide
  adj_factor = predicted / y

**Comment by gioelelm** [comment]
This is just a warning not an error right? In particular this might mean
that the default filtering parameters do not suit well your dataset or that
you have some cells that have no unspliced molecules. As I explain in the
docs the "default*" methods are examples of preprocessing that use some
heuristics (that might fail) and the user is recommended to look in the
source code and adapt the preprocessing procedure to what makes sense for
their datasets. It is in general a good practice to visualize some QC and
get to know better the quality of the data you are using.

On 26 Jan 2018 21:08, "goldfish500" <notifications@github.com> wrote:

I was using the default filtering and normalization but got this error. Is
there way to get around this? Thanks!

vlm.default_filter_and_norm()
/usr/home/anaconda3/lib/python3.6/site-packages/velocyto/analysis.py:695:
RuntimeWarning: divide by zero encountered in true_divide
adj_factor = predicted / y

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/velocyto-team/velocyto.py/issues/45>, or mute the thread
