### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by datakid** [velocyto-team/velocyto.py#46]
The documentation states that pip install velocyto should be enough. This is incorrect. As per conda, all the deps will need to be installed first.

**Comment by gioelelm** [comment]
Thank you for rasing this issue. Could you be more precise on which
commands you are running and what is failing? So that I can address the
issue.

**Comment by datakid** [comment]
Yes! Sorry.

On Centos 7.4 running Python3.6u from [IUS](https://ius.io/Packages/) (python 3.64)

I've created a virtualenv with

/usr/bin/python3.6 -m venv velocyto/0.13.4

In that, I've sourced the activate file, pip updated setuptools, then:

>(test) [root@vmpr-res-utils test]# pip install velocyto
Collecting velocyto
  Using cached velocyto-0.13.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l3p0ryp8/velocyto/setup.py", line 3, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    

So I pip installed numpy and then got:

> (test) [root@vmpr-res-utils test]# pip install velocyto
Collecting velocyto
  Using cached velocyto-0.13.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zjs39u3r/velocyto/setup.py", line 16, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    
So then I just pip installed all the reqs that were listed for conda, then velocyto installed perfectly.

**Comment by gioelelm** [comment]
Ok I see what you mean now. I think it is maybe not clear that the
requirements paragraph in the installation section refers to all the
methods of installations (pip, conda, source) .  We just suggest conda to
install these requirements since some are compiler dependent so it might
not be non trivial to get them correctly installed (for example on mac).

Anyways, it would be nice to be able to just run: pip install velocyto.
However there is the problem that numpy and cython are installation
(build-time not just runtime)  requirements  since they are needed for the
compilation step during installation. Pypi does not support this kind of
requirements (
https://stackoverflow.com/questions/36574463/install-time-dependencies-in-requirements-txt
).
I could of course catch the errors you encountered and use a precompiled C
binary estension in that case, but I guess this sort of operation is not
considered good (or safe) practice (see cython docs) .

If you have a suggestion how to make the docs clearer about this point, you
can just click on the edit on github button on the up right corner and make
your changes, I will review the changes and merge the pull request.

Thanks

On 1 Feb 2018 06:14, "Lachlan Musicman" <notifications@github.com> wrote:

Yes! Sorry.

On Centos 7.4 running Python3.6u from IUS <https://ius.io/Packages/>
(python 3.64)

I've created a virtualenv with

/usr/bin/python3.6 -m venv velocyto/0.13.4

In that, I've sourced the activate file, pip updated setuptools, then:

(test) [root@vmpr-res-utils test]# pip install velocyto
Collecting velocyto
Using cached velocyto-0.13.4.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-l3p0ryp8/velocyto/setup.py", line 3, in
import numpy as np
ModuleNotFoundError: No module named 'numpy'

So I pip installed numpy and then got:

(test) [root@vmpr-res-utils test]# pip install velocyto
Collecting velocyto
Using cached velocyto-0.13.4.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-zjs39u3r/velocyto/setup.py", line 16, in
from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
['-c', 'egg_info', '--egg-base', 'pip-egg-info']

So then I just pip installed all the reqs that were listed for conda, then
velocyto installed perfectly.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/velocyto-team/velocyto.py/issues/46#issuecomment-362160902>,
or mute the thread

**Comment by mschilli87** [comment]
see #47

**Comment by slinnarsson** [comment]
I think the docs are perfectly clear and most people have been able to follow them. If you did follow the installation docs and still have trouble, feel free to reopen. In that case, please provide a step by step example (one that does follow the installation docs, including installation of requirements before `pip install velocyto`).

**Comment by benslack19** [comment]
I know this issue is closed but thought I could share a tip as I struggled with this a little bit too. I'm using a Linux system and probably like others already had python and pip installed before I did the anaconda installation. To ensure that you're putting pysam, loompy and velocyto in the right place, you can put in your absolute path of pip associated with the conda version as in:

`/home/my_server/anaconda3/bin/pip install velocyto`

Hope this helps.

**Comment by slinnarsson** [comment]
Thanks. When you install Anaconda, make sure you say "yes" to adding the installation directory to your path, *and* to either restart your terminal or do `source ~/.bash_profile.sh` or the equivalent. If you do this, `pip` should automatically be Anaconda's `pip`. 

To verify that your path is properly configured for Anaconda, type `python` and check that it says something like:

```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Similarly `pip --version` should return:

```
pip 10.0.1 from /Users/stelin/anaconda3/lib/python3.6/site-packages/pip (python 3.6)
```

which tells you that it's the right one (because it's in the anaconda3 directory)
