### ISSUE TITLE
Velocyto on aggregated data

### ISSUE THREAD

**Issue by dpcook** [velocyto-team/velocyto.py#50]
Hey there!

I'm applying velocyto to aggregated data collected from several time points of a differentiation time course experiment. I was wondering if I should be cautious about situations where cells from different time points (eg. before and immediately after induction) may have similar gene expression, but could have different underlying velocities. Are kNNs determined based on total expression? Would the kNN smoothing be affected by this?

The reason I ask is because I'm noticing that I have cells in my non-induced population (blue) with a high velocity towards the more-differentiated populations without the accumulation of these cells at some terminal state (the cells shouldn't be dying and it seems unlikely that I managed to measure the cells just as this started to happen and they have).

Any chance you have any insight or suggestions here? Thanks! :)

Velocities produced with default pipeline (default_fit_preparation)
![velocity allcells](https://user-images.githubusercontent.com/18197806/36637677-1699da36-19af-11e8-9671-a64f31b86493.png)

**Comment by gioelelm** [comment]
Hi David,

Thank you for the interest in our work.

Yes you are totally right what you are observing is probably an artefact of
the knn averaging. Basically your data does not satisfy the assumptions of
the cells belonging to the same biological condition.

Lucky I have a fix for that, it is only moderately tested but I think it
does the job. It consists in constraining the knn graph and averaging using
a vector of labels (they can be your conditions or your clusters).
It is an option of the knn_imputation function. This option is available in
the dev branch on github so you need to install from source.

Please let me know if you need further help.

Best regards

Gioele


On 25 Feb 2018 04:16, "David Cook" <notifications@github.com> wrote:

Hey there!

I'm applying velocyto to aggregated data collected from several time points
of a differentiation time course experiment. I was wondering if I should be
cautious about situations where cells from different time points (eg.
before and immediately after induction) may have similar gene expression,
but could have different underlying velocities. Are kNNs determined based
on total expression? Would the kNN smoothing be affected by this?

The reason I ask is because I'm noticing that I have cells in my
non-induced population (blue) with a high velocity towards the
more-differentiated populations without the accumulation of these cells at
some terminal state (the cells shouldn't be dying and it seems unlikely
that I managed to measure the cells just as this started to happen and they
have).

Any chance you have any insight or suggestions here? Thanks! :)

Velocities produced with default pipeline (default_fit_preparation)
[image: velocity allcells]
<https://user-images.githubusercontent.com/18197806/36637677-1699da36-19af-11e8-9671-a64f31b86493.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/velocyto-team/velocyto.py/issues/50>, or mute the thread

**Comment by dpcook** [comment]
Hey Gioele,

Thanks for the quick reply! This is exactly what I was looking for :)

I went ahead and ran it this morning, constraining it to "clusters" (ie. experimental conditions) and it seemed to run smoothly. Interestingly, the pattern still exists. Perhaps it isn't an artifact? I'm not sure if there are any other points in the pipeline that could produce an artifact. I threw my ipynb up in a repo [here](https://github.com/dpcook/fun_analysis/blob/master/emt_velocity/emt_velocyto.ipynb) if you're curious. Here's the new plot:
![emt_velocity_allcells](https://user-images.githubusercontent.com/18197806/36646949-aabef550-1a4c-11e8-9e23-8a5e2fc0e180.png)

On a related now, I was wondering if you knew of any way to do all the model fits and velocity calculations like described here, but then run calculate_grid_arrows on subsets of the data (ie. each condition separately), followed by separate/faceted plots of plot_grid_arrows for each condition. Could be a cleaner way to visualize this.

**Comment by gioelelm** [comment]
I am very surprised that the methods has such a small effect.

Without inspecting the dataset is difficult to answer but BRCA1 rings a bell... there seem to be some cell cycle signal that has high velocity in the control. If these are cells in culture, the cell cycle signal might be quite strong and also since samples are separated by days other processes might take over velocity. The only way to diagnose problems might be to inspect several phase portrait... we will soon include some extra diagnostic tools to allow explaining the sources of the projected arrows but it is not ready yet.

A brain storming of suggestions / think that I would do if I were to analyse this dataset:
 - Try to perform a  feature selection that considers only genes with some significant dynamics over the time points but exclude the genes that seem to be expressed only at one time point (these kinf of genes can come from batch effects or they might be a symptom that the gene's dynamics is too fast to catch with respect of the sampling frequency).

- Project the velocity on the same PCA on which knn has been calculated (see vlm.pcs) ? What are the genes with major loadings (see vlm.pca)? Does it make sense to visualize the data in that subspace?
 
- Try eliminate the signal from the cell cycle and use `filter_genes_good_fit` to remove genes that have uncorrelated phase portraits. 

- On how many genes are you calculating velocity? Is there a strong size variation between condition?

- Reduce b_sight=k*8, b_maxl=k*4,  to   b_sight=k*5, b_maxl=k*3, 

- Are the outliers cells with super strong velocity also the one with smaller total unspliced? Because maybe size normalisation is inflating few genes and generating this artefact normalize_total had the argument  min_perc_U, increase it to exclude those cells from normalisation (leavign them with the same number of molecules)

And just a suggestion for visualization, the plot is very packed when plotting try int(vlm.embedding.shape[0]/2) instead of /1 to show half of the arrows.

To answer your second question, the simpler way I can think of: 
- take the source code for the function `calculate_grid_arrows ` and `plot_grid_arrows` and join them
- you enclose most of the code in a loop over the populations (for i in vlm.cluster_uid) 
- than inside the loop assign `embedding` to getattr(self, embed)[vlm.cluster_ix ==i, :], do the same for delta_embedding. It might be useful to have a new variable `embedding_all` that you use when embedding is used only to calculate extremities of the grid
- at every iteration plot on a different subplot.
If you think this plot it is a nice feature and an useful feature to add, you should open another post for a feature request, explain in detail what the function should do and the general API, and we will try to write it and integrate it into velocyto.
