### ISSUE TITLE
Splicing matrix is all 0

### ISSUE THREAD

**Issue by tmfs10** [velocyto-team/velocyto.py#60]
Hi,

I ran the following commands

`samtools sort -t CB -O BAM -o cellsorted_possorted_genome_bam.bam possorted_genome_bam.bam`
`velocyto run -b filtered_gene_bc_matrices/mm10/barcodes.tsv -m ../mm10_rmsk.gtf -o preprocessed_bam possorted_genome_bam.bam ../genes.gtf`

However the resulting splicing matrix S in the loom file seems to be all 0. I have another dataset (different conditions but same platform -- 10x) but for that, the splicing matrix looks fine (though the PCA visualization of the top 2 components is different compared to what it looks like when doing it for the counts from the 10x software processing). For a third dataset, the splicing matrix is also all 0s.

Any help would be appreciated!

--Sid

**Comment by gioelelm** [comment]
I am not sure what is going on. Everything seems fine.
Do you capture the stdout in a log file. Could you provide it? I would need to inspect that.

Also, are you using the dev branch? If not you should.

**Comment by tmfs10** [comment]
[log.txt](https://github.com/velocyto-team/velocyto.py/files/1899868/log.txt)

Hi,

I've attached the log file. I'm not using the dev branch but I compared the code between that and the version I'm using and the differences were minor (mainly one place where it said 'sam' instead of 'bam' but I corrected that manually)

**Comment by gioelelm** [comment]
I have released 0.17.0 let's see if it works there.
If not the log of the new version might give me more  insight on what is going on

**Comment by gioelelm** [comment]
Never mind, there won't be any need I found the problem! 

The problem is that you are mixing human and mouse genome annotations. Which species your experiment is about ? (or is it a crosspecies test?)

**Comment by gioelelm** [comment]
The log was sort of screaming it:

```
2018-04-10 19:59:07,281 - DEBUG - Marking up chromosome hg19_1
2018-04-10 19:59:07,281 - WARNING - The .bam file refers to a chromosome 'hg19_1+' not present in the annotation (.gtf) file
2018-04-10 20:03:16,331 - DEBUG - Marking up chromosome hg19_10
2018-04-10 20:03:16,331 - WARNING - The .bam file refers to a chromosome 'hg19_10+' not present in the annotation (.gtf) file
....
...
```

**Comment by tmfs10** [comment]
It is a cross species dataset. But I also tried this on a single species dataset and got the same problem. I can make the log file for that as well.

**Comment by tmfs10** [comment]
Also the what I'm trying to do is get the mRNA degradation rates from another dataset (as in theory those shouldn't change much between different cells?) as a check on whether the terminal state can be identified based on that alone. Does that seem like a valid way to go?

**Comment by gioelelm** [comment]
> It is a cross species dataset. But I also tried this on a single species dataset and got the same problem. I can make the log file for that as well.

Ok I see! Then it is a pretty custom analysis and definitely an use case that is not supported yet.The bug comes then from the non standard name for chromosome e.g. is "mm10_1". instead of "1" this should be consistent in the gtf and the bam file.

Furthermore, I am not sure exactly of what are the chromosome names in your files but some lines of code that might be in your way as well:

https://github.com/velocyto-team/velocyto.py/blob/master/velocyto/counter.py#L314-L315

That was an attempt to catch some inconsistency between the name of the chromosome in the gtf and the bam. Would you be able to propose a couple of lines of python that do the parsing correctly for your chromosome names but does not alterate the normal use (e.g. chr1, 1)?

If you provide that I can integrate it that in the pipeline.

> Also the what I'm trying to do is get the mRNA degradation rates from another dataset (as in theory those shouldn't change much between different cells?) as a check on whether the terminal state can be identified based on that alone. Does that seem like a valid way to go?

This is a interesting point but question falls out of the scope technical support for velocyto and it sounds to me more related to new algorithmic directions. I have thought aboutthis idea, if you want to discuss these topics please contact me privately. Thanks
