### ISSUE TITLE
adding metadata for run_smartseq2

### ISSUE THREAD

**Issue by Acribbs** [velocyto-team/velocyto.py#62]
Hi sorry if I'm missing something obvious here, but when running `run_smartseq2` is there a way of adding metadata information. 

Im currently going through the API info but can find any reference to this.

Thanks.

**Comment by gioelelm** [comment]
Sorry for the delay in the reply. I though I had reply already but I was on my phone and maybe did not go through.

The answer is that I could add it but I don't know how much sense it makes because people will have different annotation file formats, forcing them to reformat to some kind of standard table format is more time consuming for them that actually do it from loompy with some one-liner, the will look something like the following:
(I will assume that the annotation is loaded in memory as a dictionary or pandas dataframe)
```python

import loompy
with loompy.connect("my_velocyto.loom") as ds:
    # if annotation is a dictionary
    ds.ca.Age = np.array([annotation[i] for i in ds.ca.CellID]) 
    # OR if annotation is a pandas DataFrame
    ds.ca.Age = annotation.loc[ds.ca.CellID].values
```

**Comment by Acribbs** [comment]
Thanks for the reply!

Its a great tool, and im having fun running my data through it.
