### ISSUE TITLE
Support for sci-RNA-seq data

### ISSUE THREAD

**Issue by sarahhcarl** [velocyto-team/velocyto.py#69]
Hi there,

First of all, I've already run velocyto on some 10x data and it's looking really interesting, so thanks a lot for developing the tool!

I'm now hoping to compare against some data produced with the sci-RNA-seq protocol ([Cao et al. 2017](http://science.sciencemag.org/content/357/6352/661.full). At the moment I'm processing the data with [zUMIs](https://github.com/sdparekh/zUMIs), which seems to do a pretty good job of filtering the barcodes.

Now I'm trying to figure out whether it's best to try to use velocyto run directly or to adapt one of the existing shortcuts, such as run_dropest. As far as I can tell, for either one I would need to pass a list of the filtered barcodes as well as adding the barcodes as CB tag in the filtered bam files. This is not done by default with zUMIs but should be do-able. 

One thing I'm not sure about is how to handle the UMIs. In sci-RNA-seq they are concatenated together with the cell barcodes in R1. Would I need to also add them as a tag in the filtered bam file, or as part of the reads themselves?

Thanks for your help - I would appreciate any suggestions.

Best,
Sarah

**Comment by gioelelm** [comment]
Hi Sarah,

> First of all, I've already run velocyto on some 10x data and it's looking really interesting, so thanks a lot for developing the tool!

Happy to hear! Thank you for using it!

> One thing I'm not sure about is how to handle the UMIs. In sci-RNA-seq they are concatenated together with the cell barcodes in R1. Would I need to also add them as a tag in the filtered bam file, or as part of the reads themselves?

Instructions for this are at : 
http://velocyto.org/velocyto.py/tutorial/cli.html#requirements-on-the-input-files
(they were not there 24h ago so not your fault if you did not see them)

To get files in the correct format in your specific case you might have have to write your own script using [pysam](http://pysam.readthedocs.io/en/latest/api.html). I am not sure about the details about sci RNA seq pipeline but I guess you will have to use a mapping (e.g. python dictionary) linking the read unique id with the barcode, extracting this info from the fastq files. Then use pysam to write a copy of the bafile containing the tag that is the unique molecular identifier.

[DropEst](https://github.com/hms-dbmi/dropEst) is now outputing bam file in that default format allowing an agile analysis the many different techniques it supports. It does not support yet sci-RNA-seq but I expect it will in the future.

Also take into account that for the techniques where the UMI+CellBarcode alone are not complex enough to guarantee uniqueness  (I don't think that sciRNA seq is one of those though) you would have to specify ``-u chr`` so that the mapping information is used to cope with the reduce complexity the complexity.

**Comment by gioelelm** [comment]
EDITED the above

**Comment by sarahhcarl** [comment]
Thanks! The instructions for the input files are helpful, that makes it much clearer. Indeed I think it would be great if DropEst supports sci-RNA-seq in the future - that's probably the best way to go for the long term. For now I will play around with pysam and see if I can get my bam files into the correct format...

Cheers,
Sarah
