### ISSUE TITLE
run10x - No such file or directory ../_log

### ISSUE THREAD

**Issue by diazdc** [velocyto-team/velocyto.py#80]
Good day, 

I have a cell ranger (version 1.3.1) output directory. I've tried running velocyto for a 10x data as prescribed in the documentation, and I receive the following error:

`File "/anaconda3/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 77, in run10x
    if "Pipestance completed successfully!" not in open(os.path.join(samplefolder, "_log")).read():
FileNotFoundError: [Errno 2] No such file or directory: 'my_10x_directory/_log'`

I have verified that "my_10x_directory" contains the documents paths and directory mentioned in the instructions, but there appears to be a hang up with creating the log file. Thank you for your help.

**Comment by gioelelm** [comment]
Thank you for reporting!

I am just checking that the ``_log`` file created by cellranger is reporting explicitelly ``"Pipestance completed successfully!"`` message. This is  to avoid that users encounters problems with velocyto just because the cellranger run was not successful.

Are you sure the cellranger run completed correctly? 
Of course, it might be that a newer or older version of cellranger is reporting a successful run in another way; but I am not fully aware of that, sorry. Let me know if that is the case here.
I could just suppress that check and just report a warning instead of throwing an error.

**Comment by diazdc** [comment]
Indeed, it may be related to using an older version of cell ranger. We generated the data set nearly a year ago and it looks great. A warning instead of an error would be great. Thanks.

**Comment by gioelelm** [comment]
Ok it was pretty simple. 0.17.8 just released fixes your problem (just wait 5 min for the pip unpload)
