### ISSUE TITLE
mechanism of velocyto

### ISSUE THREAD

**Issue by lushjia** [velocyto-team/velocyto.py#85]
Hi, Gioelelm,
I am a little confused about some parts of the mechanism of this script. 

The first question is what the meaning of **delta_t** (time_step) is in this script.Does it have some substantive meanings or just an unit of time? If it is an unit of time, will changing of delta_t have any significance？

The second question is when estimating **α** and **γ** of each gene, all cell's data is used. Does it mean that this prediction on the premise that each gene has the same transcription and degradation velocity in all the cells. But I think at least genes should have different transcription velocity in different kind of cells.

**Comment by gioelelm** [comment]
> The first question is what the meaning of delta_t (time_step) is in this script.Does it have some substantive meanings or just an unit of time? If it is an unit of time, will changing of delta_t have any significance？

Changing delta_t corresponds to predicting a more distant future. However as we discuss in the paper the extrapolation makes some assumption (e.g. constant parameters within the extrapolation timescale) so further in time the prediction will be off because one does not take into account regulation... You can think about it as behaving as good as a first order Tailor approximation.

> The second question is when estimating α and γ of each gene, all cell's data is used. Does it mean that this prediction on the premise that each gene has the same transcription and degradation velocity in all the cells. But I think at least genes should have different transcription velocity in different kind of cells.

You reasoning is correct but the premises are wrong, since we do not try to estimate both gamma and alpha. We estimate only one parameter: gamma and then use it to estimate velocity of single cells (as a function of the difference from the unspliced / spliced to gamma) so different kind of cells can have different velocity. If you instead think that different cells can have also different gammas, this is also reasonable (indeed in the latest version of the paper we show that this is the case for very different cell types) and could be addressed with a more complex model (that of course will correspond with some kind of extra assumption) or as we do in the current method these genes are detected by some heuristic on the weirdly looking phase portrait and excluded (check out `filter_genes_by_phase_portrait`)

**Comment by gioelelm** [comment]
comment above was edited

**Comment by lushjia** [comment]
OK, I got it. Thanks for your reply.
