### ISSUE TITLE
get an error when install

### ISSUE THREAD

**Issue by wangmhan** [velocyto-team/velocyto.py#88]
Hi, 
I meet an error when install the velocyto.py: "Command "python setup.py egg_info" failed with error code 1". 
How to fix it? I am not a super user on server.
Thanks!

**Comment by gioelelm** [comment]
Are you using a conda environment as in the instructions?

**Comment by wangmhan** [comment]
Hi,

I install a local python with version 3.6.5, and it goes well as I used the
way "install from source".
After using the command: "pip install -e .", it print "Successfully
installed velocyto".
But when I try to run "velocyto --help", it turn out : velocyto: command
not found.

I have no idea what is wrong.

2018-06-26 16:13 GMT+02:00 Gioele La Manno <notifications@github.com>:

**Comment by wangmhan** [comment]
Hi,
I found velocyto in my local ./python/bin/velocyto. i
It seems executable -rwxrwxr-x, but actually when I try to use command like
this: ./velocyto --help, it failed.
And it print like below:

Traceback (most recent call last):
  File "./velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/pkg_resources/__init__.py",
line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/pkg_resources/__init__.py",
line 2693, in load_entry_point
    return ep.load()
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/pkg_resources/__init__.py",
line 2324, in load
    return self.resolve()
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/pkg_resources/__init__.py",
line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/mnt/kauffman/qiaolin/wmh/software/velocyto.py/velocyto/__init__.py",
line 15, in <module>
    from .analysis import VelocytoLoom, scatter_viz, ixs_thatsort_a2b,
load_velocyto_hdf5
  File "/mnt/kauffman/qiaolin/wmh/software/velocyto.py/velocyto/analysis.py",
line 10, in <module>
  import matplotlib.pyplot as plt
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/matplotlib/pyplot.py",
line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show =
pylab_setup()
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/matplotlib/backends/__init__.py",
line 62, in pylab_setup
    [backend_name], 0)
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py",
line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/matplotlib/backends/tkagg.py",
line 5, in <module>
    from six.moves import tkinter as Tk
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/six.py",
line 92, in __get__
    result = self._resolve()
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/six.py",
line 115, in _resolve
    return _import_module(self.mod)
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/site-packages/six.py",
line 82, in _import_module
    __import__(name)
  File
"/mnt/kauffman/qiaolin/wmh/software/python/lib/python3.6/tkinter/__init__.py",
line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

2018-06-26 16:22 GMT+02:00 menghan wang <wangmhan@gmail.com>:

**Comment by gioelelm** [comment]
> I install a local python with version 3.6.5, and it goes well as I used the
way "install from source".

Sorry, but the problem is that you are not following instructions.

Independently of the way you install you need the right dependencies in place. Some of them (cython, numpy, scipy) include compiling C and fortran code and therefore the easiest way to install is to use conda. conda offers a very controlled and reproducible sandbox environment that does not touch your systems installation.

I am happy to help users with all problems related to software installation as soon as they follow the instructions and use conda for the dependencies installation. Otherwise I have no reference system and I don't feel like it is possible to help users effectively.... I could be dealing with all the kind of weird system related and python installation problems.

Please use conda and we will have this solved in a snap! Thanks

**Comment by slinnarsson** [comment]
Hi

You probably don't have tkinter installed. There may also be some more complex issue with X windows and the selection of matplotlib backends. We strongly recommend using [Anaconda Python](https://www.anaconda.com/downloads) because it comes preinstalled with a large number of precompiled libraries and modules for scientific computing. Velocyto depends on many such libraries and you will need to install each one manually if you choose not to use conda.

I recommend starting over, with a fresh installation of Anaconda Python. It's easy to install, takes 5 mins, and does not require root access. It will install in your home directory. Once you have Anaconda Python, install velocyto according to the instructions and you should be all set!

**Comment by wangmhan** [comment]
Hi,

Thank you. It indeed a problem with tkinter.
So I follow your recommend to use Anaconda Python. After that, install
velocyto successfully!

BR

2018-06-26 17:04 GMT+02:00 Sten Linnarsson <notifications@github.com>:

**Comment by gioelelm** [comment]
:)

**Comment by MichaelPeibo** [comment]
@wangmhan Hi,
How do you fix it? I got same problem when install environment, when I tried to 'pip install pysam', I got the error report
`Command "python setup.py egg_info" failed with error code 1"` 

and I check "tk" by `conda list`, "tk" did exist.

Any suggestion? Thanks!

**Comment by MichaelPeibo** [comment]
Hi, I did installed it in Mac,
it seems pysam has some compiling or other issues on Windows system, see [pysam issue](https://github.com/pysam-developers/pysam/issues/262)

Alternatively, I installed pysam by bioconda as suggested [here](https://github.com/pysam-developers/pysam/issues/262#issuecomment-204592765)
And also as suggested by [previous issue](https://github.com/velocyto-team/velocyto.py/issues/58)
xcode-select --install and update gcc by `conda install gcc`

Finally, it worked. Cannot wait to try this method and my mac can carry it.

**Comment by wangmhan** [comment]
Hi,

It is glad to know that you fixed it.
I first installed it on the server, use their first recommendation which
need to install anaconda before install the software. When I tried to
install it on Mac, it is not smooth. It comes to many error, and I also
search a long time for the solution. I think I fixed it with the cmd like:
conda install gcc.



MichaelPeibo <notifications@github.com> 于2018年9月10日周一 上午4:44写道：

**Comment by brianpenghe** [comment]
I ran into the same error. 
While I was trying to install it using conda, I realized that it can't be installed that way, according to your instruction here: http://velocyto.org/velocyto.py/install/index.html#install-using-conda
Any solutions?

**Comment by brianpenghe** [comment]
> I ran into the same error.
> While I was trying to install it using conda, I realized that it can't be installed that way, according to your instruction here: http://velocyto.org/velocyto.py/install/index.html#install-using-conda
> Any solutions?

Actually I solved my own problem by typing:
conda install numpy scipy cython numba matplotlib scikit-learn h5py click
